# version: '3.9'

services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
      - "27018:27017"
    networks:
      - backend_network
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    container_name: iitbchat-be
    depends_on:
      - mongodb
    ports:
      - "4000:4000"
    networks:
      - backend_network
    environment:
      MONGO_URI: mongodb://mongodb:27017/iitbchat
      PORT: 4000

networks:
  backend_network:
    driver: bridge

volumes:
  mongo_data:
